# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  oc_platform.twig.antispam_extension:
    class: OC\PlatformBundle\Twig\AntispamExtension
    arguments:
      - "@oc_platform.antispam"
    tags:
      -  { name: twig.extension }

  oc_platform.beta.html_adder:
    class: OC\PlatformBundle\Beta\BetaHTML

  oc_platform.beta.listener:
    class: OC\PlatformBundle\Beta\BetaListener
    arguments:
      - "@oc_platform.beta.html_adder"
      - "2080-06-21"
    tags:
      - { name: kernel.event_listener, event: kernel.response,   method: processBeta }

  oc_platform.form.ckeditor:
    class: OC\PlatformBundle\Form\CkeditorType
    tags:
      - { name: form.type, alias: ckeditor }